--- 
title: "Estadística Aplicada"
author: "Equipo Editorial, Wulfrano Gómez Gallardo"
date: "`r Sys.Date()`"
output: pdf_document
documentclass: book
header-includes:
  - \usepackage[spanish,es-tabla]{babel}
bibliography: book.bib
biblio-style: apalike
link-citations: true
description: Descripción de mi libro.
language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    cor: 'Corolario '
    prp: 'Proposición '
    cnj: 'Conjetura '
    def: 'Definición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    proof: 'Demostración. '
    remark: 'Nota. '
    solution: 'Solución. '
  ui:
    chapter_name: 'Capítulo '
site: bookdown::bookdown_site
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.graphics.auto_pdf = TRUE)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
library(bookdown)
library(tinytex)
library(knitr)
library(tidyverse)
library(broom)
library(kableExtra)
library(car)
library(lmtest)
library(sandwich)
library(corrplot)
library(plotly)
library(GGally)
library(performance)
#citation("knitr")
#print(citation("knitr"), bibtex=TRUE)
#rstudio/bookdown-demo
```

# ANTECEDENTES
**Objetivos**
**

## Muestra y población
## Distribuciones muestrales
## Intervalos de confianza
## Pruebas de hipótesis


